# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  pull_request:
  schedule:
    - cron: '30 4 * * 1' # Every Monday @ 4h30am UTC

jobs:
   test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v6
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    - name: Create virtual environment with the matrix Python version.
      run: uv venv -p python${{ matrix.python-version }}
    - name: Install dependencies
      run: uv pip install .
    - name: Cache CASA data
      uses: actions/cache@v5
      id: casa-cache
      with:
        path: ~/.casa/data
        key: casa-data
    - name: Setup CASA data directory
      if: steps.casa-cache.outputs.cache-hit != 'true'
      run: mkdir -p ~/.casa/data
    - name: Actvate the environment and run the test
      run: |
        source .venv/bin/activate
        simms -dir "J2000,04h00m00.0s,-33d00m00s" -T vla -dt 8 -st 0.5 -sl 0.16667 -nc 32 -f0 856MHz -df 26749.9904kHz -pl XX YY -n mk64.0.5hr.10min.scan.8s.208khz.J0400-3300.ms
